worker_processes 1;

events {
	worker_connections 1024;
	use epoll;
	multi_accept on;
	accept_mutex on;
}

http {
	upstream api {
		server ${API_URL}:${API_PORT};
	}

	server {
		listen ${NGINX_PORT};

		location / {
			return 404 'Not found';
		}

		location ^~ /api {
			proxy_pass http://api;
		}
	}
}
